const names=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];
const meal=(time,title,subtitle,options,note='')=>({time,title,subtitle,options,note});
const breakfast=()=>meal('06:30','Colazione','Dolce o salata, scegli tu',[['Opzione dolce',['Yogurt greco o di soia · 200 g','Cereali / avena · 60 g','Noci / mandorle · 15 g','1 frutto']],['Opzione salata',['Pane tostato · 80 g','2 uova oppure fesa di tacchino / prosciutto crudo magro · 50–60 g','Burro di arachidi · 15 g']]],'Caffè rigorosamente senza zucchero.');
const snack=()=>meal('10:30','Spuntino','Una pausa a metà mattina',[['Scegli un’opzione',['1 frutto (es. mela o banana) oppure 1 barretta proteica']]],'Caffè senza zucchero.');
const lunch=()=>meal('13:00–14:00','Pranzo','Mensa o pasta fredda a casa',[['Opzione mensa',['Primo piatto · 80–100 g','Secondo magro · 120 g','Verdure senza olio','Pane · 50–60 g','1 frutto']],['Opzione casa · pasta fredda',['Pasta · 90–100 g','1 scatoletta di tonno al naturale, sgocciolata','1 mozzarella intera · 100 g','Mezza scatoletta di mais · circa 70 g','Pomodorini a piacere']]]);
function dayMeals(i){if(i<5){let list=[breakfast(),snack(),lunch()];if(i===0||i===2)list.push(meal('17:00','Prima di ginnastica','Spuntino pre-workout',[['Scegli un’opzione',['1 banana oppure 3–4 gallette']]]),meal('20:00','Cena','Dopo ginnastica',[['Componi il piatto',['Pane · 80–100 g oppure patate · 300 g','Pollo / tacchino · 150 g oppure pesce magro · 200 g','Verdure abbondanti']]],'Verdure con spezie o limone, senza olio.'));else list.push(meal('16:00–17:00','Spuntino','Frutto facoltativo',[['La tua pausa',['Caffè senza zucchero','1 piccolo frutto (opzionale, si può saltare)']]]),meal('18:30','Cena','Prima del basket',[['Componi il piatto',['Riso basmati o pasta · 100–120 g','Carne bianca o pesce magro · 120–150 g','Verdure cotte (es. zucchine o carote)']]],'Verdure rigorosamente senza olio. Evita salmone, broccoli, cavolfiori, cavoletti, cipolle e insalatone miste giganti prima del basket.'),meal('00:30','Dopo il basket','Nella notte successiva',[['Scegli un’opzione',['Yogurt greco / proteico · 150 g','Oppure Grana Padano / Parmigiano · 30–40 g con 2 gallette']]],'Nessun derivato del latte liquido, come indicato nel piano.'));return list;}if(i===5){const b=breakfast(),l=lunch();b.time='Mattina';l.time='Pranzo';return[b,l,meal('Sera','Pasto libero','Goditi la serata',[['Scegli quello che ti va',['Pizza con gli amici, hamburger, sushi o quello che preferisci']]],'Mantieni le buone abitudini a colazione e pranzo. Anche staccare un po’ fa parte del tuo piano.')];}return[meal('Mattina','Colazione rilassata','Anche un po’ più tardi',[['Le tue opzioni',['Pancake d’avena oppure una colazione dolce più abbondante']]]),meal('Pranzo','Il pranzo della domenica','Il tuo pasto della tradizione',[['Come preferisci',['Pasta elaborata, lasagne oppure arrosto']]],'Mangia a sazietà, senza appesantirti troppo.'),meal('Sera','Cena leggera','Per prepararti al lunedì',[['Scegli un’opzione',['Passato di verdure con crostini','Oppure riso in bianco · 70 g, con petto di pollo e insalata senza olio']]])];}
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderMeal(m,index){return `<details class="meal" ${index===0?'open':''}><summary><span class="time">${escape(m.time)}</span><div class="meal-name"><h3>${escape(m.title)}</h3><p>${escape(m.subtitle)}</p></div><span class="toggle" aria-hidden="true">+</span></summary><div class="content">${m.options.map(([heading,items])=>`<div class="option"><h4>${escape(heading)}</h4><ul>${items.map(x=>`<li>${escape(x)}</li>`).join('')}</ul></div>`).join('')}${m.note?`<p class="note">${escape(m.note)}</p>`:''}</div></details>`;}
const current=(new Date().getDay()+6)%7;let selected=current;
function render(i){selected=i;document.getElementById('days').innerHTML=names.map((n,j)=>`<button class="${j===i?'selected':''}" data-day="${j}" aria-pressed="${j===i}" aria-label="${n}"><span>${n.slice(0,3)}</span><b>${['G','B','G','B','B','•','•'][j]}</b></button>`).join('');document.getElementById('dayTitle').textContent=names[i];document.getElementById('todayLabel').textContent=i===current?'OGGI':'IL TUO GIORNO';const gym=i===0||i===2;document.getElementById('type').textContent=i>4?'Weekend':gym?'Ginnastica':'Basket';document.getElementById('training').innerHTML=i>4?'':`<div class="training"><div><p class="eyebrow">${gym?'GINNASTICA':'BASKET'}</p><strong>${gym?'18:30 – 20:00':'Dalle 22:30'}</strong></div><span class="symbol" aria-hidden="true">${gym?'↗':'◉'}</span></div>`;document.getElementById('meals').innerHTML=dayMeals(i).map(renderMeal).join('');}
document.getElementById('days').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b)render(Number(b.dataset.day));});
const swapGroups=[['Carboidrati','Equivalenze per circa 100 g di pasta / riso',['Pane bianco o integrale · 100–120 g','Patate lesse o al forno · 300–350 g','Farro, orzo, cous cous o quinoa · 100 g','Gnocchi di patate · 120 g','Per gli spuntini: 3–4 gallette in più oppure un pacchetto di cracker'],''],['Proteine','Equivalenze per circa 150 g di carne bianca',['Pesce magro (merluzzo, nasello, platessa, branzino) · 200 g','Pesce grasso (salmone) · 150 g','2 uova intere + albume in brick · 100 g','Mozzarella · 100 g oppure fiocchi di latte / ricotta · 150 g','Tonno o sgombro sgocciolato · 120–150 g','Legumi cotti (ceci, fagioli, lenticchie) · 200 g','Tofu o tempeh · 150 g'],'Con i legumi dimezza il pane o la pasta del pasto. Evita il salmone nella cena delle 18:30 prima del basket, come indicato nel piano.'],['Verdure','Sempre senza olio',['Libere e a volontà: zucchine, carote, pomodori, insalata verde, spinaci, fagiolini, finocchi','Prima del basket: meglio zucchine o carote lesse / al vapore','Da evitare a cena prima del basket (martedì, giovedì e venerdì): broccoli, cavolfiori, cavoletti, cipolle e insalatone miste giganti'],'Il piano indica di evitare le verdure che possono rallentare la digestione prima di andare in campo.']];
document.getElementById('swapContent').innerHTML=swapGroups.map(([title,sub,items,note],i)=>renderMeal(meal('',title,sub,[[sub,items]],note),i)).join('');
function view(swaps){document.getElementById('plan').hidden=swaps;document.getElementById('swaps').hidden=!swaps;['planTab','swapTab'].forEach((id,i)=>{let b=document.getElementById(id),active=Boolean(i)===swaps;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});window.scrollTo({top:0,behavior:'smooth'});}
document.getElementById('planTab').onclick=()=>view(false);document.getElementById('swapTab').onclick=()=>view(true);const help=document.getElementById('help');document.getElementById('install').onclick=()=>help.showModal();document.querySelectorAll('.close,.close-help').forEach(b=>b.onclick=()=>help.close());help.addEventListener('click',e=>{if(e.target===help){const r=help.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)help.close();}});render(selected);
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
